In [1]:
import pandas as pd
import numpy as np

SERIES

In [4]:
l1=['a','b','c','d','e']
display(type(l1))
display(l1)

ll1=pd.Series(l1)
display(type(ll1))
display(ll1)

list

['a', 'b', 'c', 'd', 'e']

pandas.core.series.Series

0    a
1    b
2    c
3    d
4    e
dtype: object

How To Create Pandas series?

#list
#tuple
#dictionary
#list with additional index list

In [6]:
#list
l1=['a','b','c']
l1=pd.Series(l1)
l1

0    a
1    b
2    c
dtype: object

In [7]:
#tuple
l1=('a','b','c')
l1=pd.Series(l1)
l1

0    a
1    b
2    c
dtype: object

In [8]:
# set
l1={'a','b','c'}
l1=pd.Series(l1)
l1

TypeError: 'set' type is unordered

In [10]:
#list with additional index list
l1=['a','b','c']
i1=['x','y','z']
s1=pd.Series(data=l1,index=i1)
s1

x    a
y    b
z    c
dtype: object

In [11]:
s1=pd.Series({
    "x":'a',
    "y":'b',
    "z":'c'
})
s1

x    a
y    b
z    c
dtype: object

In [13]:
l1=[1,2,3]
pd.Series(l1)

0    1
1    2
2    3
dtype: int64

how to change data type?

In [14]:
l1=[1,2,3]
pd.Series(l1,dtype=np.float64)

0    1.0
1    2.0
2    3.0
dtype: float64

In [15]:
l1=[1,2,3]
pd.Series(l1,dtype=np.float64,name='sid')

0    1.0
1    2.0
2    3.0
Name: sid, dtype: float64

# DataFrame

In [16]:
data=np.arange(10*5).reshape(10,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [17]:
df1=pd.DataFrame(data)
df1

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

# how to create dataframe?

#list of list
#tuple of tuple
#np 2d array
#dictionary
#we can also read any other tabular file like:excle, sql,xml,json,csv....

In [18]:
data=np.arange(10*5).reshape(10,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [21]:
l1=[[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]]

df1=pd.DataFrame(l1)
df1

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

In [22]:
l1=((0,  1,  2,  3,  4),
       ( 5,  6,  7,  8,  9),
       (10, 11, 12, 13, 14),
       (15, 16, 17, 18, 19),
       (20, 21, 22, 23, 24),
       (25, 26, 27, 28, 29),
       (30, 31, 32, 33, 34),
       (35, 36, 37, 38, 39),
       (40, 41, 42, 43, 44),
       (45, 46, 47, 48, 49))

df1=pd.DataFrame(l1)
df1

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

# create dataframe with dictionary

In [23]:
d1={
    'id':[1,2,3],
    'name':['a','b','c'],
    'course':['ai','ml','ds']
}
d1

{'id': [1, 2, 3], 'name': ['a', 'b', 'c'], 'course': ['ai', 'ml', 'ds']}

In [24]:
df1=pd.DataFrame(d1)
df1

id name course
0   1    a     ai
1   2    b     ml
2   3    c     ds

# read file any other sources

pd.read_software('url')

###for excel file####
df1 = pd.read_excel("./data.xlsx")#####
df1###

###for csv file####df1 = pd.read_csv("./f1.csv")#####
df1####

####f1 = pd.read_feather('./final_data.feather')#####
f1

###df1 = pd.read_json('https://dummyjson.com/products')#####
df1

# create data frame with column name

In [25]:
data=np.arange(10*5).reshape(10,5)
df1=pd.DataFrame(data,columns=['a','b','c','d','e'])
df1

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
8  40  41  42  43  44
9  45  46  47  48  49

In [27]:
df1.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [28]:
df1.index

RangeIndex(start=0, stop=10, step=1)

In [29]:
df1.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])